#ifndef CONFIGWRITER_H
#define CONFIGWRITER_H

#include <QString>

class QSettings;

/*
 * Generation of chirp_config.py, the file dsChirp hands to the GNU Radio
 * sounder (gr-juha/apps/chirpsounder/chirp.py).
 *
 * Reconstructed from frmMain::CreateConfigFile() @0x4511c0. Kept out of
 * frmMain so it can be tested without a QApplication; frmMain::CreateConfigFile
 * is a thin wrapper over writeChirpConfig().
 *
 * The output is byte-compared in tests against a file generated by the
 * ORIGINAL binary from the same settings (tests/golden/).
 */

/* Build the complete file contents. */
QString buildChirpConfig(QSettings &schedule, QSettings &config);

/* Build and write it. Returns false if the file could not be written. */
bool writeChirpConfig(const QString &path, QSettings &schedule, QSettings &config);

#endif /* CONFIGWRITER_H */
