/*
 * Colour maps, recovered from the binary's static initialisers.
 *
 * GENERATED by analysis/gen_colormaps.py -- do not edit by hand.
 *
 * The initialisers build the QColorLevel stops in descending order and append
 * them in reverse, so the vectors are stored ASCENDING; they are emitted that
 * way here. QIgColorMap then takes first() as the colour at the interval
 * minimum and last() as the colour at the maximum.
 */
#include "qigcolormap.h"

namespace {

const QColorLevel PDP_COLORS_DATA[] = {
    QColorLevel(0.001, QColor(255, 255, 255)),  /* WHITE */
    QColorLevel(0.001, QColor(  0,   0,  77)),  /* DARK_BLUE */
    QColorLevel(0.08, QColor(  0,   0, 204)),  /* BLUE */
    QColorLevel(0.12, QColor(  0,   0, 192)),  /* MEDIUM_BLUE */
    QColorLevel(0.16, QColor(  0,   0, 255)),  /* BLUE_2 */
    QColorLevel(0.2, QColor(  0, 192,   0)),  /* ISLAMIC_GREEN */
    QColorLevel(0.24, QColor(  0, 255,   0)),  /* LIME */
    QColorLevel(0.28, QColor(  0, 255, 255)),  /* CYAN */
    QColorLevel(0.32, QColor( 25,  25,  25)),  /* NERO */
    QColorLevel(0.36, QColor( 50,  50,  50)),  /* NIGHT_RIDER */
    QColorLevel(0.4, QColor( 75,  75,  75)),  /* CHARCOAL */
    QColorLevel(0.44, QColor( 88,  88,  88)),  /* MORTAR */
    QColorLevel(0.48, QColor(100, 100, 100)),  /* DIM_GRAY */
    QColorLevel(0.52, QColor(125, 125, 125)),  /* GREY */
    QColorLevel(0.56, QColor(150, 150, 150)),  /* SHADY_LADY */
    QColorLevel(0.6, QColor(153, 255,  77)),  /* GREEN_YELLOW */
    QColorLevel(0.64, QColor(192,   0, 192)),  /* DEEP_MAGENTA */
    QColorLevel(0.68, QColor(200, 200, 200)),  /* VERY_LIGHT_GREY */
    QColorLevel(0.72, QColor(225, 225, 225)),  /* GAINSBORO */
    QColorLevel(0.76, QColor(255, 255,   0)),  /* YELLOW */
    QColorLevel(0.8, QColor(255, 153,   0)),  /* ORANGE_PEEL */
    QColorLevel(0.84, QColor(255,   0,   0)),  /* RED */
    QColorLevel(0.88, QColor(255,   0, 255)),  /* MAGENTA */
    QColorLevel(0.92, QColor(255,   0, 255)),  /* MAGENTA */
    QColorLevel(0.96, QColor(255,   0, 255)),  /* MAGENTA */
};

const QColorLevel BLUE_BASE_COLORS_DATA[] = {
    QColorLevel(0.3333333333333333, QColor(  0,   0,  77)),  /* DARK_BLUE */
    QColorLevel(0.3333333333333333, QColor(  0,   0, 204)),  /* BLUE */
    QColorLevel(0.4444444444444444, QColor(  0, 255, 255)),  /* CYAN */
    QColorLevel(0.5555555555555556, QColor(153, 255,  77)),  /* GREEN_YELLOW */
    QColorLevel(0.6666666666666666, QColor(255, 255,   0)),  /* YELLOW */
    QColorLevel(0.7777777777777778, QColor(255, 153,   0)),  /* ORANGE_PEEL */
    QColorLevel(0.8888888888888888, QColor(255,   0,   0)),  /* RED */
};

const QColorLevel WHITE_BASE_COLORS_DATA[] = {
    QColorLevel(0.001, QColor(255, 255, 255)),  /* WHITE */
    QColorLevel(0.001, QColor(  0,   0, 204)),  /* BLUE */
    QColorLevel(0.16666666666666666, QColor(  0, 255, 255)),  /* CYAN */
    QColorLevel(0.3333333333333333, QColor(153, 255,  77)),  /* GREEN_YELLOW */
    QColorLevel(0.5, QColor(255, 255,   0)),  /* YELLOW */
    QColorLevel(0.6666666666666666, QColor(255, 153,   0)),  /* ORANGE_PEEL */
    QColorLevel(0.8333333333333334, QColor(255,   0,   0)),  /* RED */
};

const QColorLevel IG2_COLORS_DATA[] = {
    QColorLevel(0.09, QColor(  0,   0,   0)),  /* BLACK */
    QColorLevel(0.09, QColor( 88,  88,  88)),  /* MORTAR */
    QColorLevel(0.18, QColor(192,   0, 192)),  /* DEEP_MAGENTA */
    QColorLevel(0.27, QColor(255,   0, 255)),  /* MAGENTA */
    QColorLevel(0.36, QColor(  0,   0, 192)),  /* MEDIUM_BLUE */
    QColorLevel(0.45, QColor(  0,   0, 255)),  /* BLUE_2 */
    QColorLevel(0.54, QColor(  0, 192,   0)),  /* ISLAMIC_GREEN */
    QColorLevel(0.63, QColor(  0, 255,   0)),  /* LIME */
    QColorLevel(0.72, QColor(255, 255,   0)),  /* YELLOW */
    QColorLevel(0.81, QColor(255,   0,   0)),  /* RED */
    QColorLevel(0.9, QColor(255, 255, 255)),  /* WHITE */
};

const QColorLevel IG2_MOD_COLORS_DATA[] = {
    QColorLevel(0.1, QColor(255, 255, 255)),  /* WHITE */
    QColorLevel(0.1, QColor( 88,  88,  88)),  /* MORTAR */
    QColorLevel(0.2, QColor(192,   0, 192)),  /* DEEP_MAGENTA */
    QColorLevel(0.3, QColor(255,   0, 255)),  /* MAGENTA */
    QColorLevel(0.4, QColor(  0,   0, 192)),  /* MEDIUM_BLUE */
    QColorLevel(0.5, QColor(  0,   0, 255)),  /* BLUE_2 */
    QColorLevel(0.6, QColor(  0, 192,   0)),  /* ISLAMIC_GREEN */
    QColorLevel(0.7, QColor(  0, 255,   0)),  /* LIME */
    QColorLevel(0.8, QColor(255, 255,   0)),  /* YELLOW */
    QColorLevel(0.9, QColor(255,   0,   0)),  /* RED */
};

const QColorLevel GRAY_COLORS_DATA[] = {
    QColorLevel(0.09, QColor(255, 255, 255)),  /* WHITE */
    QColorLevel(0.09, QColor(225, 225, 225)),  /* GAINSBORO */
    QColorLevel(0.18, QColor(200, 200, 200)),  /* VERY_LIGHT_GREY */
    QColorLevel(0.27, QColor(175, 175, 175)),  /* DARK_GRAY */
    QColorLevel(0.36, QColor(150, 150, 150)),  /* SHADY_LADY */
    QColorLevel(0.45, QColor(125, 125, 125)),  /* GREY */
    QColorLevel(0.54, QColor(100, 100, 100)),  /* DIM_GRAY */
    QColorLevel(0.63, QColor( 75,  75,  75)),  /* CHARCOAL */
    QColorLevel(0.72, QColor( 50,  50,  50)),  /* NIGHT_RIDER */
    QColorLevel(0.81, QColor( 25,  25,  25)),  /* NERO */
    QColorLevel(0.9, QColor(  0,   0,   0)),  /* BLACK */
};

const QColorLevel RAINBOW_COLORS_DATA[] = {
    QColorLevel(0.08333333333333333, QColor(  0,   0, 255)),  /* BLUE_2 */
    QColorLevel(0.08333333333333333, QColor(  0, 124, 255)),  /* BLUE_3 */
    QColorLevel(0.16666666666666666, QColor(  0, 203, 255)),  /* BLUE_4 */
    QColorLevel(0.25, QColor(  0, 255, 255)),  /* CYAN */
    QColorLevel(0.3333333333333333, QColor(  0, 255, 203)),  /* GREEN_2 */
    QColorLevel(0.4166666666666667, QColor(  0, 255, 124)),  /* GREEN_3 */
    QColorLevel(0.5, QColor(124, 255,   0)),  /* GREEN_4 */
    QColorLevel(0.5833333333333334, QColor(203, 255,   0)),  /* YELLOW_2 */
    QColorLevel(0.6666666666666666, QColor(255, 255,   0)),  /* YELLOW */
    QColorLevel(0.75, QColor(255, 203,   0)),  /* ORANGE_2 */
    QColorLevel(0.8333333333333334, QColor(255, 124,   0)),  /* ORANGE_3 */
    QColorLevel(0.9166666666666666, QColor(255,   0,   0)),  /* RED */
};

const QColorLevel RAINBOW_WHITEBASE_COLORS_DATA[] = {
    QColorLevel(0.07692307692307693, QColor(255, 255, 255)),  /* WHITE */
    QColorLevel(0.07692307692307693, QColor(  0,   0, 255)),  /* BLUE_2 */
    QColorLevel(0.15384615384615385, QColor(  0, 124, 255)),  /* BLUE_3 */
    QColorLevel(0.23076923076923078, QColor(  0, 203, 255)),  /* BLUE_4 */
    QColorLevel(0.3076923076923077, QColor(  0, 255, 255)),  /* CYAN */
    QColorLevel(0.38461538461538464, QColor(  0, 255, 203)),  /* GREEN_2 */
    QColorLevel(0.46153846153846156, QColor(  0, 255, 124)),  /* GREEN_3 */
    QColorLevel(0.5384615384615384, QColor(124, 255,   0)),  /* GREEN_4 */
    QColorLevel(0.6153846153846154, QColor(203, 255,   0)),  /* YELLOW_2 */
    QColorLevel(0.6923076923076923, QColor(255, 255,   0)),  /* YELLOW */
    QColorLevel(0.7692307692307693, QColor(255, 203,   0)),  /* ORANGE_2 */
    QColorLevel(0.8461538461538461, QColor(255, 124,   0)),  /* ORANGE_3 */
    QColorLevel(0.9230769230769231, QColor(255,   0,   0)),  /* RED */
};

const QColorLevel IG2_BASE_COLORS_DATA[] = {
    QColorLevel(0.16666666666666666, QColor(  0,   0,   0)),  /* BLACK */
    QColorLevel(0.16666666666666666, QColor(192,   0, 192)),  /* DEEP_MAGENTA */
    QColorLevel(0.3333333333333333, QColor(  0,   0, 192)),  /* MEDIUM_BLUE */
    QColorLevel(0.5, QColor(  0, 192,   0)),  /* ISLAMIC_GREEN */
    QColorLevel(0.6666666666666666, QColor(255, 255,   0)),  /* YELLOW */
    QColorLevel(0.8333333333333334, QColor(255,   0,   0)),  /* RED */
};

const QColorLevel IG2_MOD_BASE_COLORS_DATA[] = {
    QColorLevel(0.001, QColor(255, 255, 255)),  /* WHITE */
    QColorLevel(0.001, QColor(192,   0, 192)),  /* DEEP_MAGENTA */
    QColorLevel(0.2, QColor(  0,   0, 192)),  /* MEDIUM_BLUE */
    QColorLevel(0.4, QColor(  0, 192,   0)),  /* ISLAMIC_GREEN */
    QColorLevel(0.6, QColor(255, 255,   0)),  /* YELLOW */
    QColorLevel(0.8, QColor(255,   0,   0)),  /* RED */
};

template <int N>
QVector<QColorLevel> toVector(const QColorLevel (&a)[N])
{
    QVector<QColorLevel> v;
    v.reserve(N);
    for (int i = 0; i < N; ++i)
        v.append(a[i]);
    return v;
}

} // namespace

const QVector<QColorLevel> &PDP_COLORS()
{
    static const QVector<QColorLevel> v = toVector(PDP_COLORS_DATA);
    return v;
}

const QVector<QColorLevel> &BLUE_BASE_COLORS()
{
    static const QVector<QColorLevel> v = toVector(BLUE_BASE_COLORS_DATA);
    return v;
}

const QVector<QColorLevel> &WHITE_BASE_COLORS()
{
    static const QVector<QColorLevel> v = toVector(WHITE_BASE_COLORS_DATA);
    return v;
}

const QVector<QColorLevel> &IG2_COLORS()
{
    static const QVector<QColorLevel> v = toVector(IG2_COLORS_DATA);
    return v;
}

const QVector<QColorLevel> &IG2_MOD_COLORS()
{
    static const QVector<QColorLevel> v = toVector(IG2_MOD_COLORS_DATA);
    return v;
}

const QVector<QColorLevel> &GRAY_COLORS()
{
    static const QVector<QColorLevel> v = toVector(GRAY_COLORS_DATA);
    return v;
}

const QVector<QColorLevel> &RAINBOW_COLORS()
{
    static const QVector<QColorLevel> v = toVector(RAINBOW_COLORS_DATA);
    return v;
}

const QVector<QColorLevel> &RAINBOW_WHITEBASE_COLORS()
{
    static const QVector<QColorLevel> v = toVector(RAINBOW_WHITEBASE_COLORS_DATA);
    return v;
}

const QVector<QColorLevel> &IG2_BASE_COLORS()
{
    static const QVector<QColorLevel> v = toVector(IG2_BASE_COLORS_DATA);
    return v;
}

const QVector<QColorLevel> &IG2_MOD_BASE_COLORS()
{
    static const QVector<QColorLevel> v = toVector(IG2_MOD_BASE_COLORS_DATA);
    return v;
}
