#!/usr/bin/env bash
#
# Install the sounder as a systemd service, so the station runs with nobody
# logged in and comes back on its own after a reboot.
#
#   sudo bash 18-install-service.sh [interface]
#
# What this solves that a terminal cannot: RLIMIT_RTPRIO is granted per login
# session, so a sounder started from a shell only has real-time priority if
# that shell was given it. systemd grants it to the service directly with
# LimitRTPRIO=99, and the whole prlimit/newgrp/logout question disappears.
#
# Settings live in /etc/default/ionozond and are preserved on re-run, so a
# later upgrade of the unit will not overwrite the station's own values.
set -u

DRY_RUN="${DRY_RUN:-0}"
UNIT_SRC="$(cd "$(dirname "$0")/.." && pwd)/ionozond-sounder.service"
UNIT_DST=/etc/systemd/system/ionozond-sounder.service
DEFAULTS=/etc/default/ionozond

say() { printf '%s\n' "$*"; }
run() {
    if [ "$DRY_RUN" = "1" ]; then say "    [dry-run] $*"; else eval "$*"; fi
}

if [ "$(id -u)" -ne 0 ] && [ "$DRY_RUN" != "1" ]; then
    say "run me with sudo, or DRY_RUN=1 to see what I would do"
    exit 1
fi

# ---- work out the defaults ------------------------------------------------
IFACE="${1:-}"
if [ -z "$IFACE" ]; then
    IFACE=$(ip -o route get 192.168.10.2 2>/dev/null \
            | awk '{for(i=1;i<=NF;i++) if($i=="dev") print $(i+1)}' | head -1)
    IFACE="${IFACE:-eno1}"
fi

# Whatever the USRP answers on. uhd_find_devices knows; fall back to the
# usual .2 rather than guessing something exotic.
RADIO_ADDR="${RADIO_ADDR:-}"
if [ -z "$RADIO_ADDR" ] && command -v uhd_find_devices >/dev/null 2>&1; then
    RADIO_ADDR=$(uhd_find_devices 2>/dev/null \
                 | sed -n 's/.*addr: *\([0-9.]*\).*/\1/p' | head -1)
fi
RADIO_ADDR="${RADIO_ADDR:-192.168.10.2}"

OPER="${SUDO_USER:-samsung}"
HOME_DIR=$(getent passwd "$OPER" | cut -d: -f6)
HOME_DIR="${HOME_DIR:-/home/$OPER}"

echo "--- what I found -----------------------------------------------------"
say "  operator     $OPER  (home $HOME_DIR)"
say "  interface    $IFACE"
say "  radio        $RADIO_ADDR"
say "  unit source  $UNIT_SRC"
echo

# ---- 1. site settings -----------------------------------------------------
echo "--- 1. $DEFAULTS ----------------------------------------"
if [ -f "$DEFAULTS" ]; then
    say "  exists already - leaving it alone. Current contents:"
    sed 's/^/    /' "$DEFAULTS"
    say "  (delete it and re-run to regenerate)"
else
    say "  writing it"
    if [ "$DRY_RUN" = "1" ]; then
        say "    [dry-run] would write $DEFAULTS"
    else
        cat > "$DEFAULTS" <<EOF
# ionozond sounder, read by ionozond-sounder.service.

# The USRP's address, and the interface the route to it uses.
RADIO_ADDR=$RADIO_ADDR
IFACE=$IFACE

# UDP frame size. Measured on this station: 4000 works, 8000 kills the stream
# outright even with a 9000 MTU. Unset or 0 leaves UHD to its own fallback of
# 1472, which costs packet rate. Confirm any change with a full sounding, not
# just a burst -- 17-probe-frame-size.py says why.
JUMBO=4000

# Generated by the console's parameters dialog, and where captures land.
IONOZOND_CONFIG=$HOME_DIR/chirp_config.py
IONOZOND_ARCHIVE=$HOME_DIR/ionograms/
EOF
        chmod 0644 "$DEFAULTS"
        say "  written"
    fi
fi
echo

# ---- 2. the unit ----------------------------------------------------------
echo "--- 2. $UNIT_DST ------------------"
if [ ! -f "$UNIT_SRC" ]; then
    say "  *** $UNIT_SRC is missing; is this the right checkout?"
    exit 1
fi
say "  installing, with WorkingDirectory and User set for $OPER"
if [ "$DRY_RUN" = "1" ]; then
    say "    [dry-run] would copy and rewrite the unit"
else
    sed -e "s#^WorkingDirectory=.*#WorkingDirectory=$HOME_DIR/projects/ionozond#" \
        -e "s#^User=.*#User=$OPER#" \
        -e "s#^Group=.*#Group=$OPER#" \
        "$UNIT_SRC" > "$UNIT_DST"
    chmod 0644 "$UNIT_DST"
    say "  installed"
fi
echo

# ---- 3. checks that would otherwise bite later ----------------------------
echo "--- 3. prerequisites -------------------------------------------------"
if getent group usrp >/dev/null 2>&1 && \
   getent group usrp | grep -q "[:,]${OPER}\b"; then
    say "  $OPER is in group usrp"
else
    say "  *** $OPER is NOT in group usrp -- run 12-host-tuning.sh first"
fi
if [ ! -f "$HOME_DIR/chirp_config.py" ]; then
    say "  *** $HOME_DIR/chirp_config.py does not exist yet."
    say "  *** The console writes it when you press OK in the parameters"
    say "  *** dialog. The service will fail until it is there."
fi
if ! command -v ethtool >/dev/null 2>&1; then
    say "  *** ethtool missing: sudo apt-get install -y ethtool"
fi
echo

# ---- 4. enable ------------------------------------------------------------
echo "--- 4. enabling ------------------------------------------------------"
run "systemctl daemon-reload"
run "systemctl enable ionozond-sounder"
say
say "  Not started. The console's START button opens the same radio, so the"
say "  two cannot run together -- stop the console's sounder first, then:"
say "      sudo systemctl start ionozond-sounder"
say "      journalctl -u ionozond-sounder -f"
say
say "  To go back to running it by hand:"
say "      sudo systemctl disable --now ionozond-sounder"
