#!/usr/bin/env bash
#
# Install the sounder as a systemd service, so the station runs with nobody
# logged in and comes back on its own after a reboot.
#
#   sudo bash 18-install-service.sh [interface]
#
# What this solves that a terminal cannot: RLIMIT_RTPRIO is granted per login
# session, so a sounder started from a shell only has real-time priority if
# that shell was given it. systemd grants it to the service directly with
# LimitRTPRIO=99, and the whole prlimit/newgrp/logout question disappears.
#
# Settings live in /etc/default/ionozond and are preserved on re-run, so a
# later upgrade of the unit will not overwrite the station's own values.
set -u

DRY_RUN="${DRY_RUN:-0}"
UNIT_SRC="$(cd "$(dirname "$0")/.." && pwd)/ionozond-sounder.service"
UNIT_DST=/etc/systemd/system/ionozond-sounder.service
DEFAULTS=/etc/default/ionozond

say() { printf '%s\n' "$*"; }
run() {
    if [ "$DRY_RUN" = "1" ]; then say "    [dry-run] $*"; else eval "$*"; fi
}

if [ "$(id -u)" -ne 0 ] && [ "$DRY_RUN" != "1" ]; then
    say "run me with sudo, or DRY_RUN=1 to see what I would do"
    exit 1
fi

# ---- work out the defaults ------------------------------------------------
IFACE="${1:-}"
if [ -z "$IFACE" ]; then
    IFACE=$(ip -o route get 192.168.10.2 2>/dev/null \
            | awk '{for(i=1;i<=NF;i++) if($i=="dev") print $(i+1)}' | head -1)
    IFACE="${IFACE:-eno1}"
fi

# Whatever the USRP answers on. uhd_find_devices knows; fall back to the
# usual .2 rather than guessing something exotic.
RADIO_ADDR="${RADIO_ADDR:-}"
if [ -z "$RADIO_ADDR" ] && command -v uhd_find_devices >/dev/null 2>&1; then
    RADIO_ADDR=$(uhd_find_devices 2>/dev/null \
                 | sed -n 's/.*addr: *\([0-9.]*\).*/\1/p' | head -1)
fi
RADIO_ADDR="${RADIO_ADDR:-192.168.10.2}"

OPER="${SUDO_USER:-samsung}"
HOME_DIR=$(getent passwd "$OPER" | cut -d: -f6)
HOME_DIR="${HOME_DIR:-/home/$OPER}"

echo "--- what I found -----------------------------------------------------"
say "  operator     $OPER  (home $HOME_DIR)"
say "  interface    $IFACE"
say "  radio        $RADIO_ADDR"
say "  unit source  $UNIT_SRC"
echo

# ---- 1. site settings -----------------------------------------------------
echo "--- 1. $DEFAULTS ----------------------------------------"
if [ -f "$DEFAULTS" ]; then
    # Values already set are the station's and are never touched. But a file
    # written by an older version of this script is missing whatever has been
    # added since -- and a unit that reads an unset variable fails in a way
    # that points at systemd rather than at here. So append what is absent.
    say "  exists already - keeping its values, adding anything new"
    added=0
    for pair in "PRUNE_KEEP_DAYS=7" "PRUNE_FREE_GB=50" "JUMBO=4000"                 "NAS_DEST=" "NAS_KEEP_H5_DAYS=30" "NAS_BWLIMIT=0"; do
        key="${pair%%=*}"
        if ! grep -q "^${key}=" "$DEFAULTS" 2>/dev/null; then
            say "    adding $pair"
            if [ "$DRY_RUN" != "1" ]; then
                printf '%s\n' "$pair" >> "$DEFAULTS"
            fi
            added=$((added + 1))
        fi
    done
    [ "$added" -eq 0 ] && say "    nothing missing"
    say "  current contents:"
    sed 's/^/    /' "$DEFAULTS"
else
    say "  writing it"
    if [ "$DRY_RUN" = "1" ]; then
        say "    [dry-run] would write $DEFAULTS"
    else
        cat > "$DEFAULTS" <<EOF
# ionozond sounder, read by ionozond-sounder.service.

# The USRP's address, and the interface the route to it uses.
RADIO_ADDR=$RADIO_ADDR
IFACE=$IFACE

# UDP frame size. Measured on this station: 4000 works, 8000 kills the stream
# outright even with a 9000 MTU. Unset or 0 leaves UHD to its own fallback of
# 1472, which costs packet rate. Confirm any change with a full sounding, not
# just a burst -- 17-probe-frame-size.py says why.
JUMBO=4000

# Generated by the console's parameters dialog, and where captures land.
IONOZOND_CONFIG=$HOME_DIR/chirp_config.py
IONOZOND_ARCHIVE=$HOME_DIR/ionograms/

# Pruning. A capture is 80 MB and the station writes 23 GB a day, so the raw
# .lfs files are deleted once their .lfp and .h5 products exist -- but only
# under both of these, and never without a readable .h5.
#
# PRUNE_KEEP_DAYS is a floor: nothing newer is ever deleted, whatever the disk
# looks like. It is the reprocessing window, since only the capture can be
# re-run at a different FFT length.
#
# PRUNE_FREE_GB is a ceiling: nothing is deleted at all while this much is
# already free. Set it to 0 to prune by age alone.
PRUNE_KEEP_DAYS=7
PRUNE_FREE_GB=50

# NAS. Empty NAS_DEST means this station has no NAS and the sync unit skips
# itself -- not a failure, and not something to be mailed about hourly.
#
# Either a mounted share (/mnt/nas/ionozond) or an rsync-over-ssh target
# (user@host:/volume1/ionozond). Use a key for the latter; a password on the
# command line would be readable in `ps` by every user on this host.
#
# NAS_KEEP_H5_DAYS is a floor: local archives newer than this are never
# deleted, and older ones only once rsync has confirmed by checksum that the
# NAS holds the same bytes. NAS_BWLIMIT is KB/s, 0 for no limit -- worth
# setting, since rsync and the sounder share one disk and one NIC.
NAS_DEST=
NAS_KEEP_H5_DAYS=30
NAS_BWLIMIT=0
EOF
        chmod 0644 "$DEFAULTS"
        say "  written"
    fi
fi
echo

# ---- 2. the unit ----------------------------------------------------------
echo "--- 2. $UNIT_DST ------------------"
if [ ! -f "$UNIT_SRC" ]; then
    say "  *** $UNIT_SRC is missing; is this the right checkout?"
    exit 1
fi
say "  installing, with WorkingDirectory and User set for $OPER"
if [ "$DRY_RUN" = "1" ]; then
    say "    [dry-run] would copy and rewrite the unit"
else
    sed -e "s#^WorkingDirectory=.*#WorkingDirectory=$HOME_DIR/projects/ionozond#" \
        -e "s#^User=.*#User=$OPER#" \
        -e "s#^Group=.*#Group=$OPER#" \
        "$UNIT_SRC" > "$UNIT_DST"
    chmod 0644 "$UNIT_DST"
    say "  installed"
fi
echo

# ---- 3. checks that would otherwise bite later ----------------------------
echo "--- 3. prerequisites -------------------------------------------------"
if getent group usrp >/dev/null 2>&1 && \
   getent group usrp | grep -q "[:,]${OPER}\b"; then
    say "  $OPER is in group usrp"
else
    say "  *** $OPER is NOT in group usrp -- run 12-host-tuning.sh first"
fi
if [ ! -f "$HOME_DIR/chirp_config.py" ]; then
    say "  *** $HOME_DIR/chirp_config.py does not exist yet."
    say "  *** The console writes it when you press OK in the parameters"
    say "  *** dialog. The service will fail until it is there."
fi
if ! command -v ethtool >/dev/null 2>&1; then
    say "  *** ethtool missing: sudo apt-get install -y ethtool"
fi
# The .h5 archive is on by default, and it is what lets the sounder delete the
# 80 MB captures. Without h5py the sounder keeps every one of them instead --
# safe, but 23 GB a day, and the only sign is one line at startup.
if python3 -c "import h5py" >/dev/null 2>&1; then
    say "  h5py present: the .h5 archive can be written"
else
    say "  *** h5py missing: sudo apt-get install -y python3-h5py"
    say "  *** Without it there is no .h5 archive, so the sounder will keep"
    say "  *** every .lfs capture -- about 23 GB a day at rep=300."
fi
echo

# ---- 4. enable ------------------------------------------------------------
echo "--- 4. enabling ------------------------------------------------------"
# The pruner and its timer, if h5_archive is on. Installed either way, but
# only enabled when the archive exists to prune against -- deleting captures
# with nothing but the lossy sidecar behind them is the one irreversible
# mistake available here.
for unit in ionozond-prune.service ionozond-prune.timer             ionozond-nas.service ionozond-nas.timer; do
    src="$(dirname "$UNIT_SRC")/$unit"
    if [ -f "$src" ]; then
        say "  installing $unit"
        if [ "$DRY_RUN" != "1" ]; then
            sed -e "s#^WorkingDirectory=.*#WorkingDirectory=$HOME_DIR/projects/ionozond#" \
                -e "s#^User=.*#User=$OPER#" \
                -e "s#^Group=.*#Group=$OPER#" \
                "$src" > "/etc/systemd/system/$unit"
            chmod 0644 "/etc/systemd/system/$unit"
        fi
    fi
done

run "systemctl daemon-reload"
run "systemctl enable ionozond-sounder"
say
say "  Not started. The console's START button opens the same radio, so the"
say "  two cannot run together -- stop the console's sounder first, then:"
say "      sudo systemctl start ionozond-sounder"
say "      journalctl -u ionozond-sounder -f"
say
say "  To go back to running it by hand:"
say "      sudo systemctl disable --now ionozond-sounder"
say
say "  Pruning is installed but NOT enabled. Turn on h5_archive in the"
say "  parameters dialog first, let it run a day, check the archives with"
say "      python3 tools/prune_lfs.py \$IONOZOND_ARCHIVE"
say "  which deletes nothing, and only then:"
say "      sudo systemctl enable --now ionozond-prune.timer"
say
say "  NAS sync is installed but NOT enabled, and does nothing while"
say "  NAS_DEST is empty. Set it in $DEFAULTS, check the run with"
say "      python3 tools/nas_sync.py \$IONOZOND_ARCHIVE --dest \$NAS_DEST"
say "  which uploads but deletes nothing, and then:"
say "      sudo systemctl enable --now ionozond-nas.timer"
